channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - click
  - libffi
  - libuuid
  - ncurses
  - openssl
  - pip
  - python
  - python-dotenv
  - readline
  - setuptools
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - pip:
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - idna==3.10
      - jiter==0.7.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain-core==0.3.15
      - langchain-openai==0.2.6
      - langchain-postgres==0.0.12
      - langsmith==0.1.142
      - numpy==1.26.4
      - openai==1.54.3
      - orjson==3.10.11
      - packaging==24.2
      - pgvector==0.2.5
      - psycopg==3.2.3
      - psycopg-binary==3.2.3
      - psycopg-pool==3.2.3
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.36
      - tenacity==9.0.0
      - tiktoken==0.8.0
      - tqdm==4.67.0
      - typing-extensions==4.12.2
      - urllib3==2.2.3
